name: Build New Image

on:
  push:
    branches: [ "main" ]

jobs:

  tag_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.new_version }}
      version_tag: ${{ steps.semver.outputs.new_tag }}
      commit: ${{ env.GITHUB_SHA }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Bump version and push tag
      id: semver
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        create_annotated_tag: true
      
    - name: Debug Version
      continue-on-error: true
      run: |
        echo "Output of version: ${{ steps.semver.outputs.new_version }}"
        echo "Output of version_tag: ${{ steps.semver.outputs.new_tag }}"

  create_github_tag:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release entry on GitHub
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: false
          tag: latest
          commit: ${{ needs.tag_version.outputs.commit }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true
  
  release_docker_image:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            dhoeppner/website:latest
            dhoeppner/website:${{ needs.build.outputs.new_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create_docker_tag:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create docker release
        run: docker build . --file Dockerfile --tag dhoeppner/website:latest
        
      - name: Upload to docker hub
        run: docker push dhoeppner/website:latest

