name: Build New Image

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 14.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 14.16.0

    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Run lint-staged
      uses: borales/actions-yarn@v4
      with:
        cmd: lint-staged
    # this is where I'd put tests.... if I had them.....
